apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: webapp-ctr
        image: ilabsllc/demoapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
