apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-webapp
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: svc-webapp
          servicePort: 80
